# Generated by Django 2.0.5 on 2018-07-28 15:57

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Article',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('text', models.TextField()),
                ('source', models.CharField(max_length=100)),
                ('url', models.URLField(unique=True)),
                ('slug', models.SlugField(max_length=220, unique=True)),
                ('image_url', models.URLField(blank=True)),
                ('length', models.IntegerField()),
                ('author', models.CharField(blank=True, max_length=100)),
                ('pub_date', models.DateTimeField(default=django.utils.timezone.now)),
            ],
            options={
                'ordering': ['-pub_date'],
            },
        ),
        migrations.CreateModel(
            name='Entry',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('edited', models.DateTimeField(auto_now=True)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('tagged', models.BooleanField(default=False)),
                ('user_reviewed', models.BooleanField(default=False)),
                ('slug', models.SlugField(max_length=220, unique=True)),
                ('article', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='article', to='collection.Article')),
            ],
            options={
                'verbose_name': 'Entry',
                'verbose_name_plural': 'Entries',
                'ordering': ['-article__pub_date', '-created', 'user_reviewed'],
            },
        ),
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('slug', models.SlugField(max_length=100, unique=True)),
            ],
        ),
        migrations.AddField(
            model_name='entry',
            name='tags',
            field=models.ManyToManyField(blank=True, related_name='tags', related_query_name='entries', to='collection.Tag'),
        ),
    ]
